### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by jethornton** [UnfinishedBusiness/ProfileCAD#1]
make
Creating directories
Beginning release build
Compiling: src//CAD.cpp -> build/release/CAD.o
g++: error: unrecognized command line option ‘-std=c++14’
make[1]: *** [build/release/CAD.o] Error 1
make: *** [release] Error 2
uname -a
Linux 3.4-9-rtai-686-pae #1 SMP PREEMPT Debian 3.4.55-4linuxcnc i686 i686 i686 GNU/Linux
cat /etc/*-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"

**Comment by UnfinishedBusiness** [comment]
Jethornton, It looks like your compiling with a older version of g++ that doesn't support the c++14 standards. Changed "COMPILE_FLAGS = -std=c++14 -g -fpermissive `wx-config --cxxflags`" in the make file to COMPILE_FLAGS = -std=c++11 -g -fpermissive `wx-config --cxxflags` and it should compile for you.
